### ISSUE TITLE
Builder generates incorrectly when a property has "is" prefix

### ISSUE THREAD

**Issue by grandstaish** [afcastano/AutoValuePlugin#19]
It tries to replace "is" with "set", but if you use the "set" prefix for one property then you need to use it for all of them. Because of this, properties beginning with "is" will generate a broken template.

**Comment by afcastano** [comment]
Cool, I'll look into it soon.

**Comment by afcastano** [comment]
If I understand well, the issue is when only one property starts with "is" and the rest don't follow the "getter" style. In that case, the plugin will generate the "set" prefix only for that property, which will break the generation.

If the previous is correct, one solution that I can think of would be to only generate "getter" style builder when ALL properties comply with the "getter" standard. If there is at least one that doesn't  comply then generate the traditional mehthods.

Would that work for you @grandstaish ?

**Comment by grandstaish** [comment]
Yes! I don't mind what you go with really, as long as the generated code compiles 👍. Really useful plugin btw, thank you!

**Comment by afcastano** [comment]
I have fixed this issue, you can update the plugin!
