### ISSUE TITLE
Missing fields from abstract classes

### ISSUE THREAD

**Issue by Sroka** [afcastano/AutoValuePlugin#21]
If some of the methods are declared in abstract class supertype this plugin does include those methods as an input to Auto_Value_<MyClass> constructor.

It is working fine if supertype is interface however.

**Comment by afcastano** [comment]
Sorry for the delayed response,
I will look into this over the weekend and let you know how easily would be to implement!

Thanks!

**Comment by afcastano** [comment]
Hello,
This kind of request are tricky to implement. The reason is that some extensions rely on the abstract methods to do their stuff. As I commented in  https://github.com/afcastano/AutoValuePlugin/issues/14#issuecomment-277982014 , the best solution would be to provide a settings page in which people can configure what to generate or not. I am planning to work on this but it might take some time.
Until then, I guess I wont be implementing this.

Thank you very much, and I hope this doesn't cause many problems to you.
