### ISSUE TITLE
Use an intention action instead of a menu item

### ISSUE THREAD

**Issue by evant** [afcastano/AutoValuePlugin#9]
I feel like an intention action (alt-enter) would make more sense. You can target it to only autovalue classes. This is also what the android studio's parcelable generator uses.

**Comment by afcastano** [comment]
I was thinking the same... I will consider this when implementing the next version.
You are welcome to issue a pull request... :D

Thank you very much!

**Comment by afcastano** [comment]
Hi @evant... I didn't mean to close the issue. 
The plug-in has been updated with your changes. Now we have intentions working. =)
Thank you very much for that.


I have also added support for generate menu.
I intentionally left the right click option available because many people is using it. I will consider removing it in the future.

You should be able to update the plugin from the jetbrains repository now. 

Please check and let me know or close this issue.

Thanks!

**Comment by evant** [comment]
It's working great!
